package pdf_lib.cjs.api;

@:jsRequire("pdf-lib/cjs/api/index") @valueModuleOnly extern class Index {
	/**
		******************* Appearance Provider Functions *************************
	**/
	static function normalizeAppearance<T>(appearance:ts.AnyOf2<pdf_lib.AppearanceMapping<T>, T>):pdf_lib.AppearanceMapping<T>;
	static function defaultCheckBoxAppearanceProvider(checkBox:pdf_lib.PDFCheckBox, widget:pdf_lib.PDFWidgetAnnotation):pdf_lib.AppearanceOrMapping<{
		var on : Array<pdf_lib.PDFOperator>;
		var off : Array<pdf_lib.PDFOperator>;
	}>;
	static function defaultRadioGroupAppearanceProvider(radioGroup:pdf_lib.PDFRadioGroup, widget:pdf_lib.PDFWidgetAnnotation):pdf_lib.AppearanceOrMapping<{
		var on : Array<pdf_lib.PDFOperator>;
		var off : Array<pdf_lib.PDFOperator>;
	}>;
	static function defaultButtonAppearanceProvider(button:pdf_lib.PDFButton, widget:pdf_lib.PDFWidgetAnnotation, font:pdf_lib.PDFFont):pdf_lib.AppearanceOrMapping<Array<pdf_lib.PDFOperator>>;
	static function defaultTextFieldAppearanceProvider(textField:pdf_lib.PDFTextField, widget:pdf_lib.PDFWidgetAnnotation, font:pdf_lib.PDFFont):pdf_lib.AppearanceOrMapping<Array<pdf_lib.PDFOperator>>;
	static function defaultDropdownAppearanceProvider(dropdown:pdf_lib.PDFDropdown, widget:pdf_lib.PDFWidgetAnnotation, font:pdf_lib.PDFFont):pdf_lib.AppearanceOrMapping<Array<pdf_lib.PDFOperator>>;
	static function defaultOptionListAppearanceProvider(optionList:pdf_lib.PDFOptionList, widget:pdf_lib.PDFWidgetAnnotation, font:pdf_lib.PDFFont):pdf_lib.AppearanceOrMapping<Array<pdf_lib.PDFOperator>>;
	static function layoutMultilineText(text:String, __1:pdf_lib.LayoutTextOptions):pdf_lib.MultilineTextLayout;
	static function layoutCombedText(text:String, __1:pdf_lib.LayoutCombedTextOptions):pdf_lib.CombedTextLayout;
	static function layoutSinglelineText(text:String, __1:pdf_lib.LayoutSinglelineTextOptions):pdf_lib.SinglelineTextLayout;
	static function grayscale(gray:Float):pdf_lib.Grayscale;
	static function rgb(red:Float, green:Float, blue:Float):pdf_lib.RGB;
	static function cmyk(cyan:Float, magenta:Float, yellow:Float, key:Float):pdf_lib.CMYK;
	static function setFillingColor(color:pdf_lib.Color):pdf_lib.PDFOperator;
	static function setStrokingColor(color:pdf_lib.Color):pdf_lib.PDFOperator;
	static function componentsToColor(?comps:Array<Float>, ?scale:Float):Null<pdf_lib.Color>;
	static function colorToComponents(color:pdf_lib.Color):Array<Float>;
	static function asPDFName(name:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFName;
	static function asPDFNumber(num:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFNumber;
	static function asNumber(num:ts.AnyOf2<Float, pdf_lib.PDFNumber>):Float;
	static function drawText(line:pdf_lib.PDFHexString, options:pdf_lib.DrawTextOptions):Array<pdf_lib.PDFOperator>;
	static function drawLinesOfText(lines:Array<pdf_lib.PDFHexString>, options:pdf_lib.DrawLinesOfTextOptions):Array<pdf_lib.PDFOperator>;
	static function drawImage(name:ts.AnyOf2<String, pdf_lib.PDFName>, options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var rotate : pdf_lib.Rotation; var xSkew : pdf_lib.Rotation; var ySkew : pdf_lib.Rotation; @:optional var graphicsState : ts.AnyOf2<String, pdf_lib.PDFName>; }):Array<pdf_lib.PDFOperator>;
	static function drawPage(name:ts.AnyOf2<String, pdf_lib.PDFName>, options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var xScale : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var yScale : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var rotate : pdf_lib.Rotation; var xSkew : pdf_lib.Rotation; var ySkew : pdf_lib.Rotation; @:optional var graphicsState : ts.AnyOf2<String, pdf_lib.PDFName>; }):Array<pdf_lib.PDFOperator>;
	static function drawLine(options:{ var start : { var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; }; var end : { var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; }; var thickness : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var color : Null<pdf_lib.Color>; @:optional var dashArray : Array<ts.AnyOf2<Float, pdf_lib.PDFNumber>>; @:optional var dashPhase : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var lineCap : pdf_lib.LineCapStyle; @:optional var graphicsState : ts.AnyOf2<String, pdf_lib.PDFName>; }):Array<pdf_lib.PDFOperator>;
	static function drawRectangle(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var rotate : pdf_lib.Rotation; var xSkew : pdf_lib.Rotation; var ySkew : pdf_lib.Rotation; @:optional var borderLineCap : pdf_lib.LineCapStyle; @:optional var borderDashArray : Array<ts.AnyOf2<Float, pdf_lib.PDFNumber>>; @:optional var borderDashPhase : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var graphicsState : ts.AnyOf2<String, pdf_lib.PDFName>; }):Array<pdf_lib.PDFOperator>;
	static function drawEllipsePath(config:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var xScale : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var yScale : ts.AnyOf2<Float, pdf_lib.PDFNumber>; }):Array<pdf_lib.PDFOperator>;
	static function drawEllipse(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var xScale : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var yScale : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var rotate : pdf_lib.Rotation; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var borderDashArray : Array<ts.AnyOf2<Float, pdf_lib.PDFNumber>>; @:optional var borderDashPhase : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var graphicsState : ts.AnyOf2<String, pdf_lib.PDFName>; @:optional var borderLineCap : pdf_lib.LineCapStyle; }):Array<pdf_lib.PDFOperator>;
	static function drawSvgPath(path:String, options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var rotate : pdf_lib.Rotation; var scale : Null<ts.AnyOf2<Float, pdf_lib.PDFNumber>>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var borderDashArray : Array<ts.AnyOf2<Float, pdf_lib.PDFNumber>>; @:optional var borderDashPhase : ts.AnyOf2<Float, pdf_lib.PDFNumber>; @:optional var borderLineCap : pdf_lib.LineCapStyle; @:optional var graphicsState : ts.AnyOf2<String, pdf_lib.PDFName>; }):Array<pdf_lib.PDFOperator>;
	static function drawCheckMark(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var size : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var thickness : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var color : Null<pdf_lib.Color>; }):Array<pdf_lib.PDFOperator>;
	static function rotateInPlace(options:{ var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var rotation : Int; }):Array<pdf_lib.PDFOperator>;
	static function drawCheckBox(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var thickness : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var markColor : Null<pdf_lib.Color>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var filled : Bool; }):Array<pdf_lib.PDFOperator>;
	static function drawRadioButton(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var dotColor : Null<pdf_lib.Color>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var filled : Bool; }):Array<pdf_lib.PDFOperator>;
	static function drawButton(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var textLines : Array<{ var encoded : pdf_lib.PDFHexString; var x : Float; var y : Float; }>; var textColor : pdf_lib.Color; var font : ts.AnyOf2<String, pdf_lib.PDFName>; var fontSize : ts.AnyOf2<Float, pdf_lib.PDFNumber>; }):Array<pdf_lib.PDFOperator>;
	static function drawTextLines(lines:Array<{ var encoded : pdf_lib.PDFHexString; var x : Float; var y : Float; }>, options:pdf_lib.DrawTextLinesOptions):Array<pdf_lib.PDFOperator>;
	static function drawTextField(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var textLines : Array<{ var encoded : pdf_lib.PDFHexString; var x : Float; var y : Float; }>; var textColor : pdf_lib.Color; var font : ts.AnyOf2<String, pdf_lib.PDFName>; var fontSize : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var padding : ts.AnyOf2<Float, pdf_lib.PDFNumber>; }):Array<pdf_lib.PDFOperator>;
	static function drawOptionList(options:{ var x : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var y : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var width : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var height : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var borderWidth : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var color : Null<pdf_lib.Color>; var borderColor : Null<pdf_lib.Color>; var textLines : Array<{ var encoded : pdf_lib.PDFHexString; var x : Float; var y : Float; var height : Float; }>; var textColor : pdf_lib.Color; var font : ts.AnyOf2<String, pdf_lib.PDFName>; var fontSize : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var lineHeight : ts.AnyOf2<Float, pdf_lib.PDFNumber>; var selectedLines : Array<Float>; var selectedColor : pdf_lib.Color; var padding : ts.AnyOf2<Float, pdf_lib.PDFNumber>; }):Array<pdf_lib.PDFOperator>;
	static function clip():pdf_lib.PDFOperator;
	static function clipEvenOdd():pdf_lib.PDFOperator;
	static function concatTransformationMatrix(a:ts.AnyOf2<Float, pdf_lib.PDFNumber>, b:ts.AnyOf2<Float, pdf_lib.PDFNumber>, c:ts.AnyOf2<Float, pdf_lib.PDFNumber>, d:ts.AnyOf2<Float, pdf_lib.PDFNumber>, e:ts.AnyOf2<Float, pdf_lib.PDFNumber>, f:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function translate(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function scale(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateRadians(angle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateDegrees(angle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function skewRadians(xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function skewDegrees(xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setDashPattern(dashArray:Array<ts.AnyOf2<Float, pdf_lib.PDFNumber>>, dashPhase:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function restoreDashPattern():pdf_lib.PDFOperator;
	static function setLineCap(style:pdf_lib.LineCapStyle):pdf_lib.PDFOperator;
	static function setLineJoin(style:pdf_lib.LineJoinStyle):pdf_lib.PDFOperator;
	static function setGraphicsState(state:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFOperator;
	static function pushGraphicsState():pdf_lib.PDFOperator;
	static function popGraphicsState():pdf_lib.PDFOperator;
	static function setLineWidth(width:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function appendBezierCurve(x1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x2:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y2:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x3:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y3:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function appendQuadraticCurve(x1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x2:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y2:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function closePath():pdf_lib.PDFOperator;
	static function moveTo(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function lineTo(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rectangle(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, width:ts.AnyOf2<Float, pdf_lib.PDFNumber>, height:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function square(xPos:Float, yPos:Float, size:Float):pdf_lib.PDFOperator;
	static function stroke():pdf_lib.PDFOperator;
	static function fill():pdf_lib.PDFOperator;
	static function fillAndStroke():pdf_lib.PDFOperator;
	static function endPath():pdf_lib.PDFOperator;
	static function nextLine():pdf_lib.PDFOperator;
	static function moveText(x:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function showText(text:pdf_lib.PDFHexString):pdf_lib.PDFOperator;
	static function beginText():pdf_lib.PDFOperator;
	static function endText():pdf_lib.PDFOperator;
	static function setFontAndSize(name:ts.AnyOf2<String, pdf_lib.PDFName>, size:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setCharacterSpacing(spacing:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setWordSpacing(spacing:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setCharacterSqueeze(squeeze:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setLineHeight(lineHeight:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setTextRise(rise:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setTextRenderingMode(mode:pdf_lib.TextRenderingMode):pdf_lib.PDFOperator;
	static function setTextMatrix(a:ts.AnyOf2<Float, pdf_lib.PDFNumber>, b:ts.AnyOf2<Float, pdf_lib.PDFNumber>, c:ts.AnyOf2<Float, pdf_lib.PDFNumber>, d:ts.AnyOf2<Float, pdf_lib.PDFNumber>, e:ts.AnyOf2<Float, pdf_lib.PDFNumber>, f:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateAndSkewTextRadiansAndTranslate(rotationAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateAndSkewTextDegreesAndTranslate(rotationAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function drawObject(name:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFOperator;
	static function setFillingGrayscaleColor(gray:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setStrokingGrayscaleColor(gray:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setFillingRgbColor(red:ts.AnyOf2<Float, pdf_lib.PDFNumber>, green:ts.AnyOf2<Float, pdf_lib.PDFNumber>, blue:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setStrokingRgbColor(red:ts.AnyOf2<Float, pdf_lib.PDFNumber>, green:ts.AnyOf2<Float, pdf_lib.PDFNumber>, blue:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setFillingCmykColor(cyan:ts.AnyOf2<Float, pdf_lib.PDFNumber>, magenta:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yellow:ts.AnyOf2<Float, pdf_lib.PDFNumber>, key:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setStrokingCmykColor(cyan:ts.AnyOf2<Float, pdf_lib.PDFNumber>, magenta:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yellow:ts.AnyOf2<Float, pdf_lib.PDFNumber>, key:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function beginMarkedContent(tag:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFOperator;
	static function endMarkedContent():pdf_lib.PDFOperator;
	static function radians(radianAngle:Float):pdf_lib.Radians;
	static function degrees(degreeAngle:Float):pdf_lib.Degrees;
	static function degreesToRadians(degree:Float):Float;
	static function radiansToDegrees(radian:Float):Float;
	static function toRadians(rotation:pdf_lib.Rotation):Float;
	static function toDegrees(rotation:pdf_lib.Rotation):Float;
	static function reduceRotation(?degreeAngle:Float):Int;
	static function adjustDimsForRotation(dims:{ var width : Float; var height : Float; }, ?degreeAngle:Float):{
		var width : Float;
		var height : Float;
	};
	static function rotateRectangle(rectangle:{ var x : Float; var y : Float; var width : Float; var height : Float; }, ?borderWidth:Float, ?degreeAngle:Float):{
		var x : Float;
		var y : Float;
		var width : Float;
		var height : Float;
	};
	static final PageSizes : {
		@:native("4A0")
		var FourA0 : ts.Tuple2<Float, Float>;
		@:native("2A0")
		var TwoA0 : ts.Tuple2<Float, Float>;
		var A0 : ts.Tuple2<Float, Float>;
		var A1 : ts.Tuple2<Float, Float>;
		var A2 : ts.Tuple2<Float, Float>;
		var A3 : ts.Tuple2<Float, Float>;
		var A4 : ts.Tuple2<Float, Float>;
		var A5 : ts.Tuple2<Float, Float>;
		var A6 : ts.Tuple2<Float, Float>;
		var A7 : ts.Tuple2<Float, Float>;
		var A8 : ts.Tuple2<Float, Float>;
		var A9 : ts.Tuple2<Float, Float>;
		var A10 : ts.Tuple2<Float, Float>;
		var B0 : ts.Tuple2<Float, Float>;
		var B1 : ts.Tuple2<Float, Float>;
		var B2 : ts.Tuple2<Float, Float>;
		var B3 : ts.Tuple2<Float, Float>;
		var B4 : ts.Tuple2<Float, Float>;
		var B5 : ts.Tuple2<Float, Float>;
		var B6 : ts.Tuple2<Float, Float>;
		var B7 : ts.Tuple2<Float, Float>;
		var B8 : ts.Tuple2<Float, Float>;
		var B9 : ts.Tuple2<Float, Float>;
		var B10 : ts.Tuple2<Float, Float>;
		var C0 : ts.Tuple2<Float, Float>;
		var C1 : ts.Tuple2<Float, Float>;
		var C2 : ts.Tuple2<Float, Float>;
		var C3 : ts.Tuple2<Float, Float>;
		var C4 : ts.Tuple2<Float, Float>;
		var C5 : ts.Tuple2<Float, Float>;
		var C6 : ts.Tuple2<Float, Float>;
		var C7 : ts.Tuple2<Float, Float>;
		var C8 : ts.Tuple2<Float, Float>;
		var C9 : ts.Tuple2<Float, Float>;
		var C10 : ts.Tuple2<Float, Float>;
		var RA0 : ts.Tuple2<Float, Float>;
		var RA1 : ts.Tuple2<Float, Float>;
		var RA2 : ts.Tuple2<Float, Float>;
		var RA3 : ts.Tuple2<Float, Float>;
		var RA4 : ts.Tuple2<Float, Float>;
		var SRA0 : ts.Tuple2<Float, Float>;
		var SRA1 : ts.Tuple2<Float, Float>;
		var SRA2 : ts.Tuple2<Float, Float>;
		var SRA3 : ts.Tuple2<Float, Float>;
		var SRA4 : ts.Tuple2<Float, Float>;
		var Executive : ts.Tuple2<Float, Float>;
		var Folio : ts.Tuple2<Float, Float>;
		var Legal : ts.Tuple2<Float, Float>;
		var Letter : ts.Tuple2<Float, Float>;
		var Tabloid : ts.Tuple2<Float, Float>;
	};
}