package pdf_lib.cjs.api;

@:jsRequire("pdf-lib/cjs/api/operators") @valueModuleOnly extern class Operators {
	static function clip():pdf_lib.PDFOperator;
	static function clipEvenOdd():pdf_lib.PDFOperator;
	static function concatTransformationMatrix(a:ts.AnyOf2<Float, pdf_lib.PDFNumber>, b:ts.AnyOf2<Float, pdf_lib.PDFNumber>, c:ts.AnyOf2<Float, pdf_lib.PDFNumber>, d:ts.AnyOf2<Float, pdf_lib.PDFNumber>, e:ts.AnyOf2<Float, pdf_lib.PDFNumber>, f:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function translate(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function scale(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateRadians(angle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateDegrees(angle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function skewRadians(xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function skewDegrees(xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setDashPattern(dashArray:Array<ts.AnyOf2<Float, pdf_lib.PDFNumber>>, dashPhase:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function restoreDashPattern():pdf_lib.PDFOperator;
	static function setLineCap(style:pdf_lib.LineCapStyle):pdf_lib.PDFOperator;
	static function setLineJoin(style:pdf_lib.LineJoinStyle):pdf_lib.PDFOperator;
	static function setGraphicsState(state:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFOperator;
	static function pushGraphicsState():pdf_lib.PDFOperator;
	static function popGraphicsState():pdf_lib.PDFOperator;
	static function setLineWidth(width:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function appendBezierCurve(x1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x2:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y2:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x3:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y3:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function appendQuadraticCurve(x1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y1:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x2:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y2:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function closePath():pdf_lib.PDFOperator;
	static function moveTo(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function lineTo(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rectangle(xPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yPos:ts.AnyOf2<Float, pdf_lib.PDFNumber>, width:ts.AnyOf2<Float, pdf_lib.PDFNumber>, height:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function square(xPos:Float, yPos:Float, size:Float):pdf_lib.PDFOperator;
	static function stroke():pdf_lib.PDFOperator;
	static function fill():pdf_lib.PDFOperator;
	static function fillAndStroke():pdf_lib.PDFOperator;
	static function endPath():pdf_lib.PDFOperator;
	static function nextLine():pdf_lib.PDFOperator;
	static function moveText(x:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function showText(text:pdf_lib.PDFHexString):pdf_lib.PDFOperator;
	static function beginText():pdf_lib.PDFOperator;
	static function endText():pdf_lib.PDFOperator;
	static function setFontAndSize(name:ts.AnyOf2<String, pdf_lib.PDFName>, size:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setCharacterSpacing(spacing:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setWordSpacing(spacing:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setCharacterSqueeze(squeeze:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setLineHeight(lineHeight:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setTextRise(rise:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setTextRenderingMode(mode:pdf_lib.TextRenderingMode):pdf_lib.PDFOperator;
	static function setTextMatrix(a:ts.AnyOf2<Float, pdf_lib.PDFNumber>, b:ts.AnyOf2<Float, pdf_lib.PDFNumber>, c:ts.AnyOf2<Float, pdf_lib.PDFNumber>, d:ts.AnyOf2<Float, pdf_lib.PDFNumber>, e:ts.AnyOf2<Float, pdf_lib.PDFNumber>, f:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateAndSkewTextRadiansAndTranslate(rotationAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function rotateAndSkewTextDegreesAndTranslate(rotationAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, xSkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, ySkewAngle:ts.AnyOf2<Float, pdf_lib.PDFNumber>, x:ts.AnyOf2<Float, pdf_lib.PDFNumber>, y:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function drawObject(name:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFOperator;
	static function setFillingGrayscaleColor(gray:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setStrokingGrayscaleColor(gray:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setFillingRgbColor(red:ts.AnyOf2<Float, pdf_lib.PDFNumber>, green:ts.AnyOf2<Float, pdf_lib.PDFNumber>, blue:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setStrokingRgbColor(red:ts.AnyOf2<Float, pdf_lib.PDFNumber>, green:ts.AnyOf2<Float, pdf_lib.PDFNumber>, blue:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setFillingCmykColor(cyan:ts.AnyOf2<Float, pdf_lib.PDFNumber>, magenta:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yellow:ts.AnyOf2<Float, pdf_lib.PDFNumber>, key:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function setStrokingCmykColor(cyan:ts.AnyOf2<Float, pdf_lib.PDFNumber>, magenta:ts.AnyOf2<Float, pdf_lib.PDFNumber>, yellow:ts.AnyOf2<Float, pdf_lib.PDFNumber>, key:ts.AnyOf2<Float, pdf_lib.PDFNumber>):pdf_lib.PDFOperator;
	static function beginMarkedContent(tag:ts.AnyOf2<String, pdf_lib.PDFName>):pdf_lib.PDFOperator;
	static function endMarkedContent():pdf_lib.PDFOperator;
}